manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: fujisheng
      url-base: https://github.com/fujisheng
    - name: refil
      url-base: https://github.com/refil
  projects:
    - name: zmk_ReFil
      remote: fujisheng
      revision: adv360-z3.2-2
      import: app/west.yml
  self:
    path: config
