manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: fujisheng
      url-base: https://github.com/fujisheng
  projects:
    - name: zmk
      remote: fujisheng
      revision: adv360-z3.2-beta2
      import: app/west.yml
  self:
    path: config
