manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: fujisheng
      url-base: https://github.com/fujisheng
    - name: ReFil
      url-base: https://github.com/ReFil
  projects:
    - name: zmk
      remote: ReFil
      revision: adv360-z3.2-2
      import: app/west.yml
  self:
    path: config
